language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token:
      secure: "d3ed979725861ecf336229c8b3575a1da3f7559a" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
